spring:
  application:
    name: forum
  datasource:
    url: jdbc:mysql://database-1-test.cdsga6wkuov5.ca-central-1.rds.amazonaws.com:3306/opb
    username: admin
    password: UzrxQQ1eEzYCrz98xHeu
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /api/forum